name: arozd_cv
description: Anton Rozdorozhniuk CV

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  responsive_builder: ^0.1.5
  http: ^0.12.0+4
  url_launcher: ^5.4.2
  get_it: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    # assets-generator-begin
    # assets/img/*
    - assets/img/facebook.png
    - assets/img/github.png
    - assets/img/linkedin.png
    - assets/img/profile_pic.jpg
    # assets-generator-end
    - assets/config/info.json

  fonts:
    - family: San Francisco
      fonts:
        - asset: assets/fonts/SFUIText-Regular.ttf
        - asset: assets/fonts/SFUIText-Light.ttf
          weight: 100
        - asset: assets/fonts/SFUIText-Medium.ttf
          weight: 400
        - asset: assets/fonts/SFUIText-Semibold.ttf
          weight: 600
        - asset: assets/fonts/SFUIText-Bold.ttf
          weight: 700
        - asset: assets/fonts/SFUIText-Heavy.ttf
          weight: 900
        - asset: assets/fonts/SFUIText-Italic.ttf
          style: italic
